apiVersion: apps/v1
kind: Deployment
metadata:
  name: get-headers
spec:
  selector:
    matchLabels:
      app: get-headers
  template:
    metadata:
      labels:
        app: get-headers
    spec:
      containers:
      - name: get-headers
        image: luizmandico/javagetheaders:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8765
---
apiVersion: v1
kind: Service
metadata:
  name: get-headers
spec:
  selector:
    app: get-headers
  ports:
  - port: 80
    targetPort: 8765
